services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: fastapi_user # Here in real world you would be using ${SECRET.user} or equivalents
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/  # Persist data across restarts
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fastapi_user", "-d", "fastapi_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data: